config/routes.rb
Rails.application.routes.draw do
  root 'search#index'
  get '/search', to: 'search#search', as: 'search'
  post '/search', to: 'search#search'
  devise_for :users # routes are generated by the device gem
  
  resources :categories
  resources :pois
  resources :invitations,        only: [:index, :new, :create]
  get '/invitations/:id/accept', to: 'invitations#accept',        as: :accept_invitation
  get '/invitations/:id/reject', to: 'invitations#reject',        as: :reject_invitation
  get '/friends',                to: 'invitations#friends',       as: :friends
  get '/friends/:id/delete',     to: 'invitations#remove_friend', as: :remove_friend

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def index
    @invitations = Invitation.where(to: current_user.email)
  end

  def new
    @invitation = Invitation.new
  end

  def create
    if invitation_params[:to] != current_user.email
      @invitation = Invitation.find_or_create_by(to: invitation_params[:to], from: current_user.email)

      if @invitation.save
        redirect_to root_path, notice: 'Your friend request has been succesfully sent'
      else
        render :new 
      end
    else
      redirect_to root_path, error: 'You can\'t invite yourself' 
    end
  end

  def accept
    invitation = Invitation.find_by(id: params[:id])
    friend = User.find_by(email: invitation.from)
    current_user.friends << friend
    friend.friends << current_user
    current_user.save!
    friend.save!
    invitation.destroy!
    redirect_to root_path, success: 'You have accepted the request'
  end

  def reject
    invitation = Invitation.find_by(id: params[:id])
    invitation.destroy!
    redirect_to root_path, success: 'You have rejected the request'
  end

  def friends
    @friends = current_user.friends
  end

  def remove_friend
    current_user.friends.find_by(id: params[:id]).destroy!
    redirect_to root_path, success: 'You have deleted a friend'
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def invitation_params
    params.require(:invitation).permit(:to)
  end
end

app/views/invitations/_form.html.erb
<%= form_for(@invitation) do |f| %>
  <% if @invitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invitation.errors.count, "error") %> prohibited this friend request from being send:</h2>

      <ul>
      <% @invitation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.text_field :to, autofocus: true, class: "form-control", placeholder: "Email" %>

  <div class="actions">
    <%= f.submit "Send Friend Request", class: "actions btn btn-lg btn-primary btn-block" %>
  </div>
<% end %>

app/views/invitations/friends.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <% if @friends.any? %>
        <h1>Friends List:</h1>
        <ul>
          <% @friends.each do |friend| %>
            <li>
              <kbd><%= friend.email %></kbd>
              <%= link_to 'Remove friend', remove_friend_path(friend.id), class: 'btn btn-danger btn-xs' %> 
            </li>
          <% end %>
        </ul>
      <% else %>
        <h1>You haven't added any friend yet. <%= link_to('Invite a friend', new_invitation_path, class: 'btn btn-primary') %></h1>
      <% end %>
    </div>
  </div>
</div>

app/views/invitations/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <% if @invitations.any? %>
        <h1>Pending Friend Requests:</h1>
        <ul>
          <% @invitations.each do |invitation| %>
            <li>
              From <kbd><%= invitation.from %></kbd>
              <%= link_to 'Accept request', accept_invitation_path(invitation), class: 'btn btn-success btn-xs' %> 
              <%= link_to 'Reject request', reject_invitation_path(invitation), class: 'btn btn-danger btn-xs' %> 
            </li>
          <% end %>
        </ul>
      <% else %>
        <h1>You don't have any pending friend request</h1>
      <% end %>
    </div>
  </div>
</div>

app/views/invitations/new.html.erb
<div class='form-category'>
  <h1 class='form-category-heading'>Send New Friend Request</h1>

  <%= render 'form' %>

  <%= link_to 'Back', root_path %>
</div>