config/routes.rb
Rails.application.routes.draw do
  root 'search#index'
  get '/search', to: 'search#search', as: 'search'
  post '/search', to: 'search#search'
  devise_for :users # routes are generated by the device gem
  
  resources :categories
  resources :pois
  resources :invitations,        only: [:index, :new, :create]
  get '/invitations/:id/accept', to: 'invitations#accept',        as: :accept_invitation
  get '/invitations/:id/reject', to: 'invitations#reject',        as: :reject_invitation
  get '/friends',                to: 'invitations#friends',       as: :friends
  get '/friends/:id/delete',     to: 'invitations#remove_friend', as: :remove_friend

end

app/models/poi.rb
class Poi < ActiveRecord::Base
  belongs_to :category

  validates :latitude, presence: true
  validates :longitude, presence: true
  validates :category_id, presence: true
  validates :name, presence: true


  after_create :record_activity

  def record_activity
    Activity.create! who: self.category.user, what: "created a new poi '#{self.name}'"
  end
end

app/controllers/pois_controller.rb
class PoisController < ApplicationController
  before_action :authenticate_user!
  before_action :set_poi, only: [:show, :edit, :update, :destroy]

  # GET /pois
  # GET /pois.json
  def index
    @pois = current_user.pois
  end

  # GET /pois/1
  # GET /pois/1.json
  def show
  end

  # GET /pois/new
  def new
    @poi = current_user.pois.new
  end

  # GET /pois/1/edit
  def edit
  end

  # POST /pois
  # POST /pois.json
  def create
    @poi = current_user.pois.new(poi_params)

    respond_to do |format|
      if @poi.save
        format.html { redirect_to @poi, notice: 'Poi was successfully created.' }
        format.json { render :show, status: :created, location: @poi }
      else
        format.html { render :new }
        format.json { render json: @poi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pois/1
  # PATCH/PUT /pois/1.json
  def update
    respond_to do |format|
      if @poi.update(poi_params)
        format.html { redirect_to @poi, notice: 'Poi was successfully updated.' }
        format.json { render :show, status: :ok, location: @poi }
      else
        format.html { render :edit }
        format.json { render json: @poi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pois/1
  # DELETE /pois/1.json
  def destroy
    @poi.destroy
    respond_to do |format|
      format.html { redirect_to pois_url, notice: 'Poi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poi
      @poi = current_user.pois.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poi_params
      params.require(:poi).permit(:name, :description, :category_id, :latitude, :longitude)
    end
end

app/views/pois/_form.html.erb
<%= form_for(@poi) do |f| %>
  <% if @poi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poi.errors.count, "error") %> prohibited this poi from being saved:</h2>

      <ul>
      <% @poi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "Enter Poi name" %>

  <%= f.label :description %>
  <%= f.text_area :description, autofocus: true, class: "form-control", placeholder: "Enter Poi Description" %>

  <%= f.label :category_id %>
  <%= f.select(:category_id, options_from_collection_for_select(current_user.categories, :id, :name, @poi.category_id), {include_blank: 'Select a category'}, { class: 'form-control' })  %>

  <%= f.label :latitude %>
  <%= f.text_field :latitude, autofocus: true, class: "form-control", placeholder: "Enter the latitude" %>

  <%= f.label :longitude %>
  <%= f.text_field :longitude, autofocus: true, class: "form-control", placeholder: "Enter the longitude" %>

  <div class="actions">
    <%= f.submit nil, class: "actions btn btn-lg btn-primary btn-block" %>
  </div>
  <br />

<% end %>

app/views/pois/_pois_map.html.erb
<div class="row">
  <div class="col-md-3 sidebar">
    <%= link_to 'New Poi', new_poi_path, class:'btn btn-primary' if display_new_button %>
    <h3>Poi List:</h3>
      <% @pois.each do |poi| %>
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title"><%= poi.name %></h3>
          </div>
          <% if poi.description.present? %>
            <div class="panel-body">
              <%= poi.description %>
            </div>
          <% end %>
          <% if display_poi_actions %>
            <div class="panel-footer">
              <%= link_to 'Edit', edit_poi_path(poi), class: 'btn btn-primary btn-xs'%>
              <%= link_to 'Delete', poi, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs'%>
            </div>
          <% end %>
        </div>
      <% end %>
  </div>
  <div class="col-md-9 main">
    <script type="text/javascript">
      function initialize() {

        var map = new google.maps.Map(document.getElementById("map-canvas"), {zoom: 15});
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position){
            var userLocation = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
            map.setCenter(userLocation);
            var userMarker= new google.maps.Marker({
              position: userLocation,
              map: map,
              icon: 'https://cdn3.iconfinder.com/data/icons/iconic-1/32/map_pin_fill-64.png',
              title: "Your current location"
             });
            var infoWindowForUserMarker = new google.maps.InfoWindow({
               content: "Your current location"
             });

             google.maps.event.addListener(userMarker, 'click', function() {
               infoWindowForUserMarker.open(map, userMarker);
             });
          });
        }

        <% pois.each do |poi| %>

             var poiMarker<%= poi.id %> = new google.maps.Marker({
              position: new google.maps.LatLng(<%= poi.latitude %>,<%= poi.longitude %>),
              map: map,
              icon: 'https://cdn1.iconfinder.com/data/icons/Map-Markers-Icons-Demo-PNG/48/Map-Marker-Flag--Right-Chartreuse.png',
              title: "<%= poi.name %>"
             });

             var infoWindowForMarker<%= poi.id %> = new google.maps.InfoWindow({
               content: "<%= poi.description %>"
             });

             google.maps.event.addListener(poiMarker<%= poi.id %>, 'click', function() {
               infoWindowForMarker<%= poi.id %>.open(map, poiMarker<%= poi.id %>);
             });

        <% end %>
      }

      google.maps.event.addDomListener(window, 'load', initialize);

    </script>

    <div id="map-canvas"></div>
  </div>
</div>

app/views/pois/edit.html.erb
<div class="form-poi">
  <h1 class="form-poi-heading">Editing poi</h1>
  <%= render 'form' %>
  <%= link_to 'Show', @poi %> |
  <%= link_to 'Back', pois_path %>
</div>

app/views/pois/index.html.erb
<div class="row">
  <div class="col-md-3 sidebar">
      <%= link_to 'New Poi', new_poi_path, class:'btn btn-primary' %>
      <h3>Pois List:</h3>
      <% @pois.each do |poi| %>
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title"><%= poi.name %></h3>
          </div>
          <div class="panel-body">
            <%= poi.description %>
          </div>
          <div class="panel-footer">
            <%= link_to 'Edit', edit_poi_path(poi), class: 'btn btn-info btn-xs' %>
            <%= link_to 'Delete', poi, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
          </div>
        </div>
      <% end %>
  </div>
  <div class="col-md-9 main">
    <script type="text/javascript">
      function initialize() {

        var map = new google.maps.Map(document.getElementById("map-canvas"), {zoom: 12});
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position){
            var userLocation = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
            map.setCenter(userLocation);
          });
        }

        <% @pois.each do |poi| %>

             var poiMarker<%= poi.id %> = new google.maps.Marker({
              position: new google.maps.LatLng(<%= poi.latitude %>,<%= poi.longitude %>),
              map: map,
              title: "<%= poi.name %>"
             });

             var infoWindowForMarker<%= poi.id %> = new google.maps.InfoWindow({
               content: "<%= poi.description %>"
             });

             google.maps.event.addListener(poiMarker<%= poi.id %>, 'click', function() {
               infoWindowForMarker<%= poi.id %>.open(map, poiMarker<%= poi.id %>);
             });

        <% end %>
      }

      google.maps.event.addDomListener(window, 'load', initialize);

    </script>

    <div id="map-canvas"></div>
  </div>
</div>

app/views/pois/new.html.erb
<div class="form-poi">
  <h1 class="form-poi-heading">New poi</h1>
  <%= render 'form' %>
  <%= link_to 'Back', pois_path %>
</div>

app/views/pois/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @poi.name %>
</p>

<%= link_to 'Edit', edit_poi_path(@poi) %> |
<%= link_to 'Back', pois_path %>