config/routes.rb
Rails.application.routes.draw do
  root 'search#index'
  get '/search', to: 'search#search', as: 'search'
  post '/search', to: 'search#search'
  devise_for :users # routes are generated by the device gem
  
  resources :categories
  resources :pois
  resources :invitations,        only: [:index, :new, :create]
  get '/invitations/:id/accept', to: 'invitations#accept',        as: :accept_invitation
  get '/invitations/:id/reject', to: 'invitations#reject',        as: :reject_invitation
  get '/friends',                to: 'invitations#friends',       as: :friends
  get '/friends/:id/delete',     to: 'invitations#remove_friend', as: :remove_friend

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whereabout</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyBZuBULFNVKHkibpTcLOOwoZR5QwPg6VIs"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script type="text/javascript">
    $(document).ready(function(){
      var autocomplete = new google.maps.places.Autocomplete(
         (document.getElementById('address')), { types: ['geocode'] }
      );
      google.maps.event.addListener(autocomplete, 'place_changed', function() {
       console.log(autocomplete);
      });

      if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(function(position) {
          var geolocation = new google.maps.LatLng(
              position.coords.latitude, position.coords.longitude);
          autocomplete.setBounds(new google.maps.LatLngBounds(geolocation,
              geolocation));
        });
      }
      console.log("autocomplete loaded!");
    });
    
  </script>

</head>

<body>
  <!-- Fixed navbar -->
  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Whereabout", root_path, class: "navbar-brand" %>
      </div>
      <div class="navbar-collapse collapse">
          <%= form_tag(search_path, method: :post, class: 'navbar-form navbar-left') %>
          <div class="row">
            <div class="form-group">
              <%= select_tag(:category_id, options_from_collection_for_select(@system_categories, :id, :name), {include_blank: 'Select a category', class: 'form-control' } )%>
            </div>
            <div class="form-group">
              <%= text_field_tag :address, nil, placeholder: 'Enter and address', class: 'form-control' %>
            </div>
            <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-search"></span></button>
          </div>
        </form>

        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="glyphicon glyphicon-envelope"></span> (<%= @invitations.size %>)
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to('View friend requests', invitations_path) %></li>
              <li><%= link_to('Invite a friend', new_invitation_path) %></li>
              <li><%= link_to('View Friends', friends_path) %></li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= image_tag current_user.gravatar_url %> <%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to('My Account', edit_user_registration_path) %></li>
              <li><%= link_to('My Categories ', categories_path) %></li>
              <li><%= link_to('My Pois ', pois_path) %></li>
            </ul>
          </li>
          <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
        </ul>

      </div><!--/.nav-collapse -->
    </div>
  </div>

  <div class="container-fluid">  

    <% if @invitations.any? %>
      <%= content_tag(:div, id: "flash_alert", class: "alert alert-warning alert-dismissible", role: "alert" ) do %>
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
        You have <%= pluralize(@invitations.size, 'pending friend request') %>.
      <% end %>
    <% end %>

    <%= render "flash_messages" %>

    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/no_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whereabout</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "flash_messages" %>
    <%= yield %>
  </div>

</body>
</html>